# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - taxually-landing-api

on:
  push:
    branches:
      - dockerized
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_64c3d4a55e27449daf1d49a27775ca28 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6f663a700f1b4a43800ed70c4e75aac9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_64c3d4a55e27449daf1d49a27775ca28 }}/node:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'taxually-landing-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4924cc8fe32b4516ab70f39e10937d39 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_64c3d4a55e27449daf1d49a27775ca28 }}/node:${{ github.sha }}'